### ISSUE TITLE
Should we have node_modules committed?

### ISSUE THREAD

**Issue by gnarf** [jquery/jquery-release#76] opened 2015-03-03 18:25 UTC
This apparently saves some dangerous/places a release could go wrong situation, but I think that it's going to create problems for cross platform if the deps ever end up with compiled gyp modules for instance.

It's generally not a good idea to have them committed to the best of my understanding.  Thoughts?

**Comment by markelog** [comment] 2015-03-03 18:33
shrinkwrap? Although i remember there was some issues with it.

> This apparently saves some dangerous/places a release could go wrong situation

Was there a precedent?

**Comment by scottgonzalez** [comment] 2015-03-03 18:37
We can just have the release script install its own dependencies as the first step.

**Comment by arthurvr** [comment] 2015-03-03 18:44
Sure. There are definitely disadvantages with having it in the repo.

**Comment by dmethvin** [comment] 2015-03-03 18:45
Most dependencies are nailed to a specific version which is good, so having it install dependencies should be relatively low risk.

**Comment by mzgol** [comment] 2015-03-03 18:52
@dmethvin 
> Most dependencies are nailed to a specific version which is good, so having it install dependencies should be relatively low risk.

The problem is that only direct dependencies are specified this way. You can't count on `npm install` done some time later producing the same dependency tree.

@gnarf 
> I think that it's going to create problems for cross platform if the deps ever end up with compiled gyp modules for instance.

This is supposed to be taken care of by `node-gyp rebuild`. That said, npm@3 will dedupe by default so the current tree won't be what it'd produce; the logical dependency tree will be decoupled from the directory one. I'm not sure how it'll play with dep structure created via npm@1.4 or 2.x (perhaps @othiym23 would know more).

Shrinkwrap was created for this use case. It still has some problems, e.g. it doesn't warn against mismatches between `package.json` & `npm-shrinkwrap.json` (it just ignores the former), it doesn't work with `npm install --save` out of the box etc. This, again, should be taken care of in the nearby future but we're not there yet.

**Comment by arschmitz** [comment] 2015-03-03 18:52
@dmethvin that assumes any dependencies of our dependencies use fixed versions

**Comment by dmethvin** [comment] 2015-03-03 18:55
@arschmitz @mzgol Oh yeah I always forget that you're only as unvarying as your sloppiest dependency. Shrinkwrap may be a safer option.

**Comment by markelog** [comment] 2015-03-03 19:05
@dmethvin @arschmitz fixed deps are not ideal, but it has is a very low risk that the same features of the dependancy wouldn't work the same way, since deps of the dep are encapsulated.

I wonder if somebody actually face any inconsistencies with fixed deps, yeah, theoretically it's possible, but practically?

I think if there wasn't any issues with it, we shouldn't try to fix something that's not broken. shrinkwrap is pretty radical.

**Comment by othiym23** [comment] 2015-03-03 22:57
I would recommend testing shrinkwrap as a group and seeing how you feel about the result. @mzgol is that we're making some improvements to shrinkwrap in `npm@3`, and he's also right that it's probably going to be a little while until `npm@3` is stable enough for this use case. In the meantime, if there are bugs that block you using it to distribute jQuery, we're happy to work with you to smooth out those edges (especially if there are patches included).

Because npm has to bootstrap itself, all its production dependencies are `bundledDependences` and checked into Git; it also doesn't / can't have any native modules in the dependencies. Those two constraints sort of cancel each other out, but there are special tests cases to ensure that `node_modules` is in sync with both `bundledDependencies` and `dependencies`. In practice, this is a pretty low-key workflow, and it ensures that everyone doing releases is releasing the same bits, but it doesn't play very nice with native modules and does require a certain amount of extra discipline.

**Closed** 2021-03-01 21:37 UTC
